name: LectureImageProcessing2022
dependencies:
  - python=3.7
  - conda-forge::jupyter
  - matplotlib>=3.5.0
  - numpy>=1.21.0
  - scikit-image>=0.19.0
  - conda-forge::itk>=5.2.0
  - conda-forge::itkwidgets>=0.32.0
  - tqdm>=4.50.0
  - pandas>=1.3.0
  - openpyxl>=3.0.0
  - imagecodecs>=2020.12.22
#  - rise
#  - pip>=20.0.0
#  - pip:
#      - matplotlib>=3.5.0
#      - numpy>=1.21.0
#      - scikit-image>=0.19.0
#      - itk>=5.2.0
#      - itkwidgets>=0.30.0
#      - tqdm>=4.50.0
#      - pandas>=1.3.0
#      - openpyxl>=3.0.0
#      - jupyter_contrib_nbextensions

