name: LectureImageProcessing2022
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyter
  - matplotlib
  - numpy
  - scikit-image
  - itk
  - itkwidgets=0.32.0
  - rise
  - pip
  - pip:
      - jupyter_contrib_nbextensions

